# 1. Edit this file with your configuration
# 2. Save as "config.toml" in the project root directory

[display]
# Inky Impression 4"
width = 640
height = 400

# Inky Impression 5.7"
# width = 600
# height = 448

[spot]
name = "Pendower Beach"
latitude = 50.204553
longitude = -4.947837

[stormglass]
api_key = "(your stormglass.io API key)"
data_source_preference = ["meto", "noaa", "sg"]
